/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc.h"

float *
add_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static float  result;
	printf("add(%f,%f) is called....\n",argp->a,argp->b );
	result = argp->a + argp->b;
	return &result;
}

float *
sub_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static float  result;
	printf("substract(%f,%f) is called....\n",argp->a,argp->b );
	result = argp->a - argp->b;
	return &result;
}

float *
mul_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static float  result;
	printf("multiply(%f,%f) is called....\n",argp->a,argp->b );
	result = argp->a * argp->b;
	return &result;
}

float *
div_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static float  result;
	printf("division(%f,%f) is called....\n",argp->a,argp->b );
	result = argp->a / argp->b;
	return &result;
}
