/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "fact.h"

int *
fact_1_svc(int *argp, struct svc_req *rqstp)
{
	static int  result;

	int temp = argp[0];

	printf("factorial(%d) called\n",temp);

	if(temp>=0){
		if(temp==0)
			temp=1;
		result = temp;

		while(temp!=1){
			temp--;
			result*=temp;
		}
	}
	else{
		result=-1;
	}

	return &result;
}
