/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "temp.h"


void
temp_prog_1(char *host)
{
	CLIENT *clnt;
	numbers  *result_1;
	numbers  temp_1_arg;
    printf("\nEnter size of array :");
	int n;
	scanf("%d",&n);
	temp_1_arg.n=n;
	printf("\nEnter elements of array :");
	for(int i=0;i<temp_1_arg.n;i++){
		int k;
		scanf("%d",&k);
		temp_1_arg.arr[i]=k;
	}
#ifndef	DEBUG
	clnt = clnt_create (host, TEMP_PROG, TEMP_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = temp_1(&temp_1_arg, clnt);
	if (result_1 == (numbers *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else{
		for(int i=0;i<temp_1_arg.n;i++){
			printf("\nmin : %d",result_1->min);
			printf("\nmax : %d",result_1->max);
			printf("\navg : %d",result_1->avg);
		}
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	temp_prog_1 (host);
exit (0);
}
