/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "find_max.h"


void
find_max_prog_1(char *host,data *input)
{
	CLIENT *clnt;
	int  *result_1;
	data  find_max_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, FIND_MAX_PROG, FIND_MAX_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	
	find_max_1_arg = *input;
	result_1 = find_max_1(&find_max_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else{
		printf("Maximum element : %d",*result_1);
	}
	printf("\n");
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	int size,i;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];

	printf("Enter the size of array: ");
	scanf("%d",&size);
	if(size>0){
		data input;
		input.sz=size;
		printf("Enter the elements: ");
		for(i=0; i<size; i++){
			scanf("%d",&(input.arr[i]));
		}
		find_max_prog_1 (host,&input);
	}
exit (0);
}
