/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _FIND_MAX_H_RPCGEN
#define _FIND_MAX_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct data {
	int arr[100];
	int sz;
};
typedef struct data data;

#define FIND_MAX_PROG 0x1212111
#define FIND_MAX_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define find_max 1
extern  int * find_max_1(data *, CLIENT *);
extern  int * find_max_1_svc(data *, struct svc_req *);
extern int find_max_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define find_max 1
extern  int * find_max_1();
extern  int * find_max_1_svc();
extern int find_max_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_data (XDR *, data*);

#else /* K&R C */
extern bool_t xdr_data ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_FIND_MAX_H_RPCGEN */
