/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "ans.h"

bool_t
xdr_input (XDR *xdrs, input *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->size))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->str, 50,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_number (XDR *xdrs, number *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->a))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->b))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_num_arr (XDR *xdrs, num_arr *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, (1 +  50 )* BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->size))
				 return FALSE;
			 if (!xdr_vector (xdrs, (char *)objp->arr, 50,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
		} else {
			IXDR_PUT_LONG(buf, objp->size);
			{
				register int *genp;

				for (i = 0, genp = objp->arr;
					i < 50; ++i) {
					IXDR_PUT_LONG(buf, *genp++);
				}
			}
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, (1 +  50 )* BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->size))
				 return FALSE;
			 if (!xdr_vector (xdrs, (char *)objp->arr, 50,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
		} else {
			objp->size = IXDR_GET_LONG(buf);
			{
				register int *genp;

				for (i = 0, genp = objp->arr;
					i < 50; ++i) {
					*genp++ = IXDR_GET_LONG(buf);
				}
			}
		}
	 return TRUE;
	}

	 if (!xdr_int (xdrs, &objp->size))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->arr, 50,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_stat (XDR *xdrs, stat *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->maximum))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->minimum))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->avg))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_two_str (XDR *xdrs, two_str *objp)
{
	register int32_t *buf;

	 if (!xdr_input (xdrs, &objp->s1))
		 return FALSE;
	 if (!xdr_input (xdrs, &objp->s2))
		 return FALSE;
	return TRUE;
}
