/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "ans.h"

int *
polindrome_1_svc(input *argp, struct svc_req *rqstp)
{
	static int  result;

	int i=0;
	int m = argp[0].size/2;
	int l = argp[0].size-1;
	printf("server is running....");

	for(i=0;i<m;i++){
		if((argp[0].str)[i] != (argp[0].str)[l-i]){
			result = 0;
			return &result;
		}
	}

	result = 1;

	return &result;
}

int *
check_leap_year_1_svc(int *argp, struct svc_req *rqstp)
{
	static int result;

    int leap = argp[0];

	if(leap % 4 == 0 && ((leap % 400 == 0) || (leap %100 != 0))){
	     result = 1;
		 return &result;
	}else{
	result = 0;

	return &result;

	}
}

int *
gcd_1_svc(number *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

double *
sqr_root_1_svc(int *argp, struct svc_req *rqstp)
{
	static double  result;

	/*
	 * insert server code here
	 */

	return &result;
}

number *
swap_1_svc(number *argp, struct svc_req *rqstp)
{
	static number  result;

	/*
	 * insert server code here
	 */

	return &result;
}

stat *
getstat_1_svc(num_arr *argp, struct svc_req *rqstp)
{
	static stat  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
comp_str_1_svc(two_str *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
chk_substr_1_svc(two_str *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

input *
concate_1_svc(two_str *argp, struct svc_req *rqstp)
{
	static input  result;

	/*
	 * insert server code here
	 */

	return &result;
}

num_arr *
reverse_1_svc(num_arr *argp, struct svc_req *rqstp)
{
	static num_arr  result;

	/*
	 * insert server code here
	 */

	return &result;
}
