/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "ans.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
sol_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		input polindrome_1_arg;
		int check_leap_year_1_arg;
		number gcd_1_arg;
		int sqr_root_1_arg;
		number swap_1_arg;
		num_arr getstat_1_arg;
		two_str comp_str_1_arg;
		two_str chk_substr_1_arg;
		two_str concate_1_arg;
		num_arr reverse_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case polindrome:
		_xdr_argument = (xdrproc_t) xdr_input;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) polindrome_1_svc;
		break;

	case check_leap_year:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) check_leap_year_1_svc;
		break;

	case gcd:
		_xdr_argument = (xdrproc_t) xdr_number;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) gcd_1_svc;
		break;

	case sqr_root:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_double;
		local = (char *(*)(char *, struct svc_req *)) sqr_root_1_svc;
		break;

	case swap:
		_xdr_argument = (xdrproc_t) xdr_number;
		_xdr_result = (xdrproc_t) xdr_number;
		local = (char *(*)(char *, struct svc_req *)) swap_1_svc;
		break;

	case getstat:
		_xdr_argument = (xdrproc_t) xdr_num_arr;
		_xdr_result = (xdrproc_t) xdr_stat;
		local = (char *(*)(char *, struct svc_req *)) getstat_1_svc;
		break;

	case comp_str:
		_xdr_argument = (xdrproc_t) xdr_two_str;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) comp_str_1_svc;
		break;

	case chk_substr:
		_xdr_argument = (xdrproc_t) xdr_two_str;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) chk_substr_1_svc;
		break;

	case concate:
		_xdr_argument = (xdrproc_t) xdr_two_str;
		_xdr_result = (xdrproc_t) xdr_input;
		local = (char *(*)(char *, struct svc_req *)) concate_1_svc;
		break;

	case reverse:
		_xdr_argument = (xdrproc_t) xdr_num_arr;
		_xdr_result = (xdrproc_t) xdr_num_arr;
		local = (char *(*)(char *, struct svc_req *)) reverse_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (SOL_PROG, SOL_VERS);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, SOL_PROG, SOL_VERS, sol_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (SOL_PROG, SOL_VERS, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, SOL_PROG, SOL_VERS, sol_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (SOL_PROG, SOL_VERS, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
