/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SOLU_H_RPCGEN
#define _SOLU_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct number {
	int arr[100];
	int a;
	int b;
};
typedef struct number number;

#define SOLU_PROG 0x123456
#define SOLU_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define slou 1
extern  number * slou_1(number *, CLIENT *);
extern  number * slou_1_svc(number *, struct svc_req *);
extern int solu_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define slou 1
extern  number * slou_1();
extern  number * slou_1_svc();
extern int solu_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_number (XDR *, number*);

#else /* K&R C */
extern bool_t xdr_number ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SOLU_H_RPCGEN */
