/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "prime_check.h"

int *
prime_check_1_svc(int *argp, struct svc_req *rqstp)
{
	static int  result;
	int i;

	printf("prime_check(%d) is called.....\n",*argp);

	if(*argp <= 1)
		result=0;
	else{
		result=1;
		for(i=2; i*i <= *argp; i++){
			if(*argp % i == 0){
				result=0;
				break;
			}
		}
	}
	return &result;
}
