/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "prime_check.h"


void
primecheck_prog_1(char *host, int x)
{
	CLIENT *clnt;
	int  *result_1;
	int  prime_check_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, PRIMECHECK_PROG, PRIMECHECK_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	prime_check_1_arg = x;

	result_1 = prime_check_1(&prime_check_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else{
		if(*result_1 == 0)
			printf("\n%d is not a prime number.\n",x);
		else
			printf("\n%d is a prime number.\n",x);
	}

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	int x;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];

	printf("\nEnter the number: ");
	scanf("%d",&x);

	primecheck_prog_1 (host,x);
exit (0);
}
