/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _FIBB_H_RPCGEN
#define _FIBB_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct data {
	int arr[50];
	int sz;
};
typedef struct data data;

#define FIBB_PROG 0x111111
#define FIBB_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define find_fibb 1
extern  data * find_fibb_1(int *, CLIENT *);
extern  data * find_fibb_1_svc(int *, struct svc_req *);
extern int fibb_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define find_fibb 1
extern  data * find_fibb_1();
extern  data * find_fibb_1_svc();
extern int fibb_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_data (XDR *, data*);

#else /* K&R C */
extern bool_t xdr_data ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_FIBB_H_RPCGEN */
